"""
    Ensemble des requetes SQL utilisées dans le programme
"""

SELECT_CATEGORIE_D = '''
        SELECT CATEGORIE_T AS GROSSE_CATEGORIE_DE_DEPENSE, 
               SUM(TRANS_VAL) AS TOTAL_DEPENSE
        FROM F_TRANSACTION
        JOIN D_INFO_T ON F_TRANSACTION.INFO_FK = D_INFO_T.ALL_IN
        WHERE CODE_FK = 'D'
        GROUP BY CATEGORIE_T
        ORDER BY TOTAL_DEPENSE ASC
        FETCH FIRST ROW ONLY
'''

SELECT_CATEGORIE_C = '''
        SELECT SOUS_CATEGORIE_T AS GROSSE_SOUS_CATEGORIE_DE_REVENUS, 
               SUM(TRANS_VAL) AS TOTAL_REVENUS
        FROM F_TRANSACTION
        JOIN D_INFO_T ON F_TRANSACTION.INFO_FK = D_INFO_T.ALL_IN
        WHERE CODE_FK = 'C'
        GROUP BY SOUS_CATEGORIE_T
        ORDER BY TOTAL_REVENUS DESC
        FETCH FIRST ROW ONLY
'''

SELECT_SOLDE_CLIENT = '''
        SELECT DATE_FK AS DATE_TRANSACTION,
               SUM(CASE WHEN CODE_FK = 'C' THEN TRANS_VAL ELSE -TRANS_VAL END) AS SOLDE_CLIENT
        FROM F_TRANSACTION
        GROUP BY DATE_FK
        ORDER BY DATE_FK
'''

__all__ = [
    'SELECT_CATEGORIE_D',
    'SELECT_CATEGORIE_C',
    'SELECT_SOLDE_CLIENT'
]
